### PR TITLE
fix numeric only layout

### PR DESCRIPTION
**Pull request by My1**
the icons seem to be imgs rather than directly SVG tags.
image

### CODE REVIEW

**Comment by joamjoamjoam** [comment]
Steam deck or holo iso?

What steam client channel? (Stable or beta)

It seems to be working on my steam deck i vet the numeric only layout no icons.

**Comment by My1** [comment]
steam deck
beta
3.3.2
OS Build: 20221005.1

Client Build Date: 13th oct 2022 22:42 UTC+1

**Comment by joamjoamjoam** [comment]
Ah i see it now. Its in the changelogs for the beta client. Can you update the PR to use both the img and the svg tags. That should wprk for both beta and stable.

**Comment by My1** [comment]
sure I can try.
btw assuming you are joamjoamjoam#1331 on discord I contacted you regarding a bigger thing I cooked up last night

**Comment by My1** [comment]
that should do it

**Comment by My1** [comment]
Can be closed as of #5

**Pull request closed without merging**
